spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-demo
    username: postgres
    password: u#FZ@qmA287
    driverClassName: org.postgresql.Driver